// Personal setup uses the URL fragment, which is not sent to GitHub Pages.
try{const fragment=new URLSearchParams(location.hash.slice(1));const origin=fragment.get('from');if(origin&&/^[a-zA-Z0-9.%-]+,[a-zA-Z0-9.%-]+,[^/]+,,ADDRESS_POI$/.test(origin)){localStorage.setItem('naver-origin-segment',origin);localStorage.setItem('commute-origin',decodeURIComponent(origin.split(',')[2]));history.replaceState(null,'',location.pathname+location.search)}}catch{}
const $=s=>document.querySelector(s);let commuteOrigin='';try{commuteOrigin=localStorage.getItem('commute-origin')||''}catch{};let saved=Archive.saved;let tab='all',filter='all';const expanded=new Set();
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const isNew=j=>JOBS.some(x=>x.id===j.id)&&(j.addedBatch===window.JOB_UPDATE?.id||(window.JOB_UPDATE?.newIds||[]).includes(j.id));
const bookmark='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M6 4h12v17l-6-4-6 4z"/></svg>';
function salaryReview(j){return ['negotiable','company-policy','undisclosed'].includes(j.salaryType)||/협의|면접\s*후\s*결정|회사\s*내규|급여\s*미기재/.test(j.pay||'')}
function activeCandidate(j){return !j.outOfScope&&!['마감','원문 삭제','마감일 경과','확인 필요 · 검색 누락'].includes(Archive.state(j))}
function render(){const current=Archive.jobs.filter(activeCandidate);const total=current.filter(j=>!salaryReview(j)).length;const negotiating=current.filter(salaryReview).length;document.querySelector('[data-tab=all]').textContent='현재 후보('+String(total).padStart(2,'0')+')';document.querySelector('[data-tab=salary]').textContent='급여 협의('+String(negotiating).padStart(2,'0')+')';document.querySelector('[data-tab=archive]').textContent='누적 공고('+String(Archive.jobs.length).padStart(2,'0')+')';$('#salary-note').hidden=tab!=='salary';$('#saved-count').textContent=saved.length;const nc=JOBS.filter(isNew).length;$('#update-counts').innerHTML='<strong>이번 갱신</strong> <span class="'+(nc?'new-count':'')+'">신규 '+nc+'건</span> · 조건 변경 '+(window.JOB_UPDATE?.changedIds||[]).length+'건(자료 보완 포함) · 신규 마감 '+(window.JOB_UPDATE?.closedIds||[]).length+'건';const q=$('#search').value.trim().toLowerCase();const jobs=Archive.jobs.filter(j=>tab==='archive'||(tab==='saved'?saved.includes(j.id):activeCandidate(j)&&(tab==='salary'?salaryReview(j):!salaryReview(j)))).filter(j=>(filter==='all'||(filter==='special'?j.specialNotes?.length:filter==='stretch'?j.stretch:classify(j)===filter))&&[j.company,j.role,j.region,j.duties].join(' ').toLowerCase().includes(q)).sort((a,b)=>Number(isNew(b))-Number(isNew(a)));$('#result-count').textContent=`${tab==='archive'?'누적 공고':tab==='saved'?'관심 공고':tab==='salary'?'급여 확인 후보':'검토 후보'} ${jobs.length}곳`;
$('#jobs').innerHTML=jobs.length?jobs.map(j=>{const expired=Archive.state(j)==='마감일 경과';const route=naverRoute(j);return `<article class="job compact ${isNew(j)?'is-new':''}"><div class="compact-head"><button class="row-toggle" data-expand="${j.id}" aria-expanded="${expanded.has(j.id)}" aria-controls="preview-${j.id}">${isNew(j)?'<span class="new-badge">NEW 신규</span>':''}<span class="row-top"><span class="company">${esc(j.company)}</span><span class="salary">${esc(j.pay)}</span></span><span class="row-role">${esc(j.role)}</span><span class="row-info">${esc(j.region)} · ${esc(j.hours)}</span>${j.specialNotes?.length?`<span class="special-notes"><b>특이사항</b> ${j.specialNotes.map(esc).join(' · ')}</span>`:''}<span class="row-status">${esc(Archive.state(j))} · ${esc(classify(j))}<span class="expand-hint">${expanded.has(j.id)?'요약 접기 −':'요약 보기 ＋'}</span></span></button><div class="row-tools"><button class="save" data-save="${j.id}" aria-label="${esc(j.company)} 관심 공고 ${saved.includes(j.id)?'해제':'저장'}" aria-pressed="${saved.includes(j.id)}">${bookmark}</button><button class="copy-job" data-copy="${esc(j.id)}" aria-label="${esc(j.company)} 공고 복사">복사</button></div></div><div class="preview" id="preview-${j.id}" ${expanded.has(j.id)?'':'hidden'}><div class="preview-facts">${esc(j.contract)} · ${esc(j.employees||'직원 수 확인 필요')}<br>통근 거리·시간 확인 필요 · ${esc(j.deadlineText)}</div><p class="why"><strong>검토 이유</strong> ${esc(j.why)}</p><p class="warning">${esc(j.caution)}</p>${j.outOfScope?'<p class="warning">현재 검색 기준에서 제외 · 기록은 보관</p>':''}${Archive.management(j)}<details><summary>상세 보기</summary><div class="detail"><dl><dt>회사·업체 내역</dt><dd>${esc(j.business)}</dd><dt>직원 수</dt><dd>${esc(j.employees||'확인된 자료 없음 · 채용 인원과 구분')}</dd><dt>근무지 주소</dt><dd>${esc(j.address)}</dd><dt>집에서 거리</dt><dd>기준: ${esc(commuteOrigin||'평택시 동삭동 · 대략적 기준')}<br>차량 km·분 미확인. 자동차 길찾기로 열립니다. 출발지를 한 번 연결하면 이후 자동 입력됩니다.</dd><dt>담당 업무</dt><dd>${esc(j.duties)}</dd><dt>근무조건</dt><dd>${esc(j.hours)}<br>${esc(j.contract)}</dd><dt>급여조건</dt><dd>${esc(j.pay)}<br>${esc(j.annual)}<br>공고 월급 × 12 단순 환산. 상여·퇴직금·식대 포함과 세전 여부는 별도 확인.</dd><dt>복리후생</dt><dd>${esc(j.benefit)}</dd><dt>지원 전 확인</dt><dd>${esc(j.checks)}<br>공통: 실제 좌식 업무 비중·급여 인상 규정은 미확인</dd><dt>마감</dt><dd>${esc(j.deadlineText)}${expired?' · 마감일이 지났습니다':''}</dd></dl><div class="actions"><a class="primary" target="_blank" rel="noopener noreferrer" href="${esc(j.url)}">공고 원문 보기 ↗</a><a class="secondary" target="_blank" rel="noopener noreferrer" href="${esc(route)}">네이버 지도 · 길찾기 ↗</a></div><p class="source-note">${window.NAVER_DESTINATIONS?.[j.id]?'자동차·도착지 자동 선택. 연결한 출발지를 사용합니다.':'새 공고는 네이버 주소 검색으로 열립니다. 검색한 장소에서 길찾기를 선택해주세요.'}</p><p class="source-note">출처: ${esc(j.source)} · ${esc(j.status)}<br>검토 이유는 공고를 바탕으로 한 판단이며 회사의 근무환경을 보증하지 않습니다.</p></div></details></div></article>`}).join(''):`<div class="empty">${tab==='salary'?'현재 등록된 급여 협의·미정 공고가 없습니다.<br>다음 검색부터 급여가 미정이어도 다른 조건이 맞으면 이곳에 추가합니다.':'조건에 맞는 공고가 없습니다.<br>검색어나 필터를 바꿔보세요.'}</div>`;
document.querySelectorAll('[data-expand]').forEach(b=>b.onclick=()=>{const id=b.dataset.expand;const open=!expanded.has(id);if(open)expanded.add(id);else expanded.delete(id);document.getElementById('preview-'+id).hidden=!open;b.setAttribute('aria-expanded',String(open));b.querySelector('.expand-hint').textContent=open?'요약 접기 −':'요약 보기 ＋';syncMaster()});document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{const id=b.dataset.save;saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];Archive.saved=saved;Archive.persist();render()});document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copyJob(b.dataset.copy));Archive.bind();syncMaster();}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',3000)}
function classify(j){if(/접수|수납|원무/.test(j.role))return '고객·접수';const t=j.role+' '+j.duties;if(/경리|회계|급여.*보험/.test(t))return '경리·회계';if(/간호|입소자|진료.*보조/.test(t))return '의료·돌봄';if(/교육|출결|수강/.test(t))return '교육행정';if(/예약|일정.*조율/.test(t))return '예약·일정';if(/수발주|주문|납기/.test(t))return '주문·수발주';if(/접수|수납|인바운드|전화 응대|고객지원/.test(t))return '고객·접수';if(/사무|행정|문서/.test(t))return '사무·행정';return '기타·확인 필요'}
document.querySelector('.filters').innerHTML=['all',...new Set(Archive.jobs.map(classify)),'stretch','special'].map(x=>`<button data-filter="${esc(x)}" class="${x==='all'?'active':''}">${esc(x==='all'?'전체':x==='special'?'특이사항':x==='stretch'?'조건 좋은 제안':x)}</button>`).join('');
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('selected',x===b));filter='all';$('#search').value='';document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'));$('#criteria').hidden=tab!=='criteria';$('#logs').hidden=tab!=='logs';$('#career').hidden=tab!=='career';document.querySelector('main').classList.toggle('career-mode',tab==='career');$('#results').hidden=['criteria','logs','career'].includes(tab);document.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-current',x.dataset.tab===tab?'page':'false'));b.scrollIntoView({block:'nearest',inline:'nearest'});render()});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));render()});$('#search').oninput=render;$('#update').onclick=()=>$('#help').showModal();$('#close-help').onclick=()=>$('#help').close();
if(Date.now()-new Date(window.JOB_UPDATE?.id||'2026-09-17T03:28+09:00').getTime()>86400000*2){$('#stale').hidden=false;$('#stale').textContent='공고 확인 후 2일 이상 지났습니다. 오늘 모집 여부를 다시 확인해주세요.'}render();

$('#update-mobile').onclick=()=>$('#help').showModal();Archive.bindBackup();

$('#commute-origin').value=commuteOrigin;
$('#save-origin').onclick=()=>{commuteOrigin=$('#commute-origin').value.trim();try{localStorage.setItem('commute-origin',commuteOrigin);localStorage.removeItem('naver-origin-segment');$('#naver-origin-status').textContent='출발지 변경됨 · 링크를 다시 연결해주세요';toast('출발지를 이 브라우저에 저장했습니다.')}catch{toast('저장 제한: 현재 화면에서만 사용합니다.')}render()};

function naverRoute(j){const dest=window.NAVER_DESTINATIONS?.[j.id];let origin='-';try{origin=localStorage.getItem('naver-origin-segment')||'-'}catch{}return dest?'https://map.naver.com/p/directions/'+origin+'/'+dest+'/-/car':'https://map.naver.com/p/search/'+encodeURIComponent(j.address)}
$('#save-naver-origin').onclick=()=>{try{const url=new URL($('#naver-origin-link').value.trim());if(url.hostname!=='map.naver.com'||!url.pathname.startsWith('/p/directions/'))throw Error();const origin=url.pathname.split('/')[3];if(!origin||origin==='-'||origin.split(',').length<3)throw Error();localStorage.setItem('naver-origin-segment',origin);commuteOrigin=decodeURIComponent(origin.split(',')[2]);localStorage.setItem('commute-origin',commuteOrigin);$('#commute-origin').value=commuteOrigin;$('#naver-origin-link').value='';$('#naver-origin-status').textContent='출발지 연결 완료 · 이 브라우저에서 자동 입력';render();toast('출발지 연결 완료')}catch{toast('출발지를 지정한 네이버 웹 길찾기 전체 주소를 붙여넣어주세요.')}};
try{if(localStorage.getItem('naver-origin-segment'))$('#naver-origin-status').textContent='출발지 연결 완료 · 이 브라우저에서 자동 입력'}catch{}

function syncMaster(){const rows=[...document.querySelectorAll('[data-expand]')];const all=rows.length>0&&rows.every(b=>b.getAttribute('aria-expanded')==='true'&&document.querySelector('#preview-'+b.dataset.expand+' > details')?.open);const b=$('#toggle-all');b.disabled=!rows.length;b.textContent=all?'전체 접기':'전체 펼치기';b.setAttribute('aria-expanded',String(all));}
$('#toggle-all').onclick=()=>{const open=$('#toggle-all').getAttribute('aria-expanded')!=='true';document.querySelectorAll('[data-expand]').forEach(b=>{const id=b.dataset.expand;if(open)expanded.add(id);else expanded.delete(id);b.setAttribute('aria-expanded',String(open));b.querySelector('.expand-hint').textContent=open?'요약 접기 −':'요약 보기 ＋';const preview=document.getElementById('preview-'+id);preview.hidden=!open;preview.querySelectorAll('details').forEach(d=>d.open=open)});syncMaster()};
document.querySelector('#jobs').addEventListener('toggle',syncMaster,true);

function jobShareText(j){return [`[${j.company}] ${j.role}`,`급여: ${j.pay}`,`근무: ${j.hours}`,`지역: ${j.region}`,...(j.specialNotes?.length?[`특이사항: ${j.specialNotes.join(' · ')}`]:[]),`상태: ${Archive.state(j)} · ${j.deadlineText}`,`원문: ${j.url}`].join('\n')}
async function copyJob(id){const j=Archive.jobs.find(x=>x.id===id);if(!j)return;const text=jobShareText(j);try{if(!navigator.clipboard?.writeText)throw Error();await Promise.race([navigator.clipboard.writeText(text),new Promise((_,reject)=>setTimeout(()=>reject(Error("clipboard timeout")),2000))]);toast('공고 복사 완료 · 카톡에 붙여넣으세요.')}catch{const d=$('#copy-dialog');$('#copy-text').value=text;d.showModal();$('#copy-text').focus();$('#copy-text').select();}}
$('#close-copy').onclick=()=>$('#copy-dialog').close();

$('#copy-update').onclick=async()=>{const input=$('#update-request');try{if(!navigator.clipboard?.writeText)throw Error();await Promise.race([navigator.clipboard.writeText(input.value),new Promise((_,reject)=>setTimeout(()=>reject(Error()),2000))]);$('#copy-update-status').textContent='복사 완료! 이 대화에 붙여넣어 보내주세요. GitHub 푸시·배포 확인까지 요청됩니다.'}catch{input.focus();input.select();$('#copy-update-status').textContent='자동 복사가 제한됩니다. 선택된 문장을 길게 누르거나 Ctrl+C로 복사해주세요.'}};

// Only the explicit Home button resets the view; the title is plain text.
document.querySelector('#home').addEventListener('click',()=>{
 if(/^#career(?:-|$)/.test(location.hash))history.replaceState(null,'',location.pathname+location.search);
 expanded.clear();
 document.querySelectorAll('details[open]').forEach(d=>d.open=false);
 document.querySelector('[data-tab="all"]').click();
 document.querySelectorAll('nav,.filters').forEach(el=>el.scrollLeft=0);
 window.scrollTo({top:0,left:0,behavior:'instant'});
});

// Direct links open the career page before scrolling to its section.
if(/^#career(?:-|$)/.test(location.hash)){document.querySelector('[data-tab=career]').click();requestAnimationFrame(()=>document.querySelector(location.hash)?.scrollIntoView({block:'start'}));}
