const $=s=>document.querySelector(s);let commuteOrigin='';try{commuteOrigin=localStorage.getItem('commute-origin')||''}catch{};let saved=Archive.saved;let tab='all',filter='all';const expanded=new Set();
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const isNew=j=>JOBS.some(x=>x.id===j.id)&&(j.addedBatch===window.JOB_UPDATE?.id||(window.JOB_UPDATE?.newIds||[]).includes(j.id));
const bookmark='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M6 4h12v17l-6-4-6 4z"/></svg>';
function render(){const total=Archive.jobs.filter(j=>!j.outOfScope&&!['마감','원문 삭제','마감일 경과','확인 필요 · 검색 누락'].includes(Archive.state(j))).length;document.querySelector('[data-tab=all]').textContent='현재 후보('+String(total).padStart(2,'0')+')'; document.querySelector('[data-tab=archive]').textContent='누적 공고('+String(Archive.jobs.length).padStart(2,'0')+')';$('#saved-count').textContent=saved.length;const nc=JOBS.filter(isNew).length;$('#update-counts').innerHTML='<strong>이번 갱신</strong> <span class="'+(nc?'new-count':'')+'">신규 '+nc+'건</span> · 조건 변경 '+(window.JOB_UPDATE?.changedIds||[]).length+'건';const q=$('#search').value.trim().toLowerCase();const jobs=Archive.jobs.filter(j=>(tab==='saved'||tab==='archive'||(!j.outOfScope&&!['마감','원문 삭제','마감일 경과','확인 필요 · 검색 누락'].includes(Archive.state(j))))) .filter(j=>(tab!=='saved'||saved.includes(j.id))&&(filter==='all'||(filter==='stretch'?j.stretch:classify(j)===filter))&&[j.company,j.role,j.region,j.duties].join(' ').toLowerCase().includes(q)).sort((a,b)=>Number(isNew(b))-Number(isNew(a)));$('#result-count').textContent=`${tab==='archive'?'누적 공고':tab==='saved'?'관심 공고':'검토 후보'} ${jobs.length}곳`;
$('#jobs').innerHTML=jobs.length?jobs.map(j=>{const expired=j.deadline&&new Date()>new Date(j.deadline+'T23:59:59+09:00');const route='https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(commuteOrigin||'경기도 평택시 동삭동')+'&destination='+encodeURIComponent(j.address)+'&travelmode=driving';return `<article class="job compact ${isNew(j)?'is-new':''}"><div class="compact-head"><button class="row-toggle" data-expand="${j.id}" aria-expanded="${expanded.has(j.id)}" aria-controls="preview-${j.id}">${isNew(j)?'<span class="new-badge">NEW 신규</span>':''}<span class="row-top"><span class="company">${esc(j.company)}</span><span class="salary">${esc(j.pay)}</span></span><span class="row-role">${esc(j.role)}</span><span class="row-info">${esc(j.region)} · ${esc(j.hours)}</span><span class="row-status">${esc(Archive.state(j))} · ${esc(classify(j))}<span class="expand-hint">${expanded.has(j.id)?'요약 접기 −':'요약 보기 ＋'}</span></span></button><button class="save" data-save="${j.id}" aria-label="${esc(j.company)} 관심 공고 ${saved.includes(j.id)?'해제':'저장'}" aria-pressed="${saved.includes(j.id)}">${bookmark}</button></div><div class="preview" id="preview-${j.id}" ${expanded.has(j.id)?'':'hidden'}><div class="preview-facts">${esc(j.contract)} · 직원 수 확인 필요<br>통근 거리·시간 확인 필요 · ${esc(j.deadlineText)}</div><p class="why"><strong>검토 이유</strong> ${esc(j.why)}</p><p class="warning">${esc(j.caution)}</p>${j.outOfScope?'<p class="warning">현재 검색 기준에서 제외 · 기록은 보관</p>':''}${Archive.management(j)}<details><summary>상세 보기</summary><div class="detail"><dl><dt>회사·업체 내역</dt><dd>${esc(j.business)}</dd><dt>직원 수</dt><dd>확인된 자료 없음 · 채용 인원과 구분</dd><dt>근무지 주소</dt><dd>${esc(j.address)}</dd><dt>집에서 거리</dt><dd>기준: ${esc(commuteOrigin||'평택시 동삭동 · 대략적 기준')}<br>차량 km·분 미확인. 아래 차량 경로에서 확인할 수 있습니다.</dd><dt>담당 업무</dt><dd>${esc(j.duties)}</dd><dt>근무조건</dt><dd>${esc(j.hours)}<br>${esc(j.contract)}</dd><dt>급여조건</dt><dd>${esc(j.pay)}<br>${esc(j.annual)}<br>공고 월급 × 12 단순 환산. 상여·퇴직금·식대 포함과 세전 여부는 별도 확인.</dd><dt>복리후생</dt><dd>${esc(j.benefit)}</dd><dt>지원 전 확인</dt><dd>${esc(j.checks)}<br>공통: 실제 좌식 업무 비중·급여 인상 규정은 미확인</dd><dt>마감</dt><dd>${esc(j.deadlineText)}${expired?' · 마감일이 지났습니다':''}</dd></dl><div class="actions"><a class="primary" target="_blank" rel="noopener noreferrer" href="${esc(j.url)}">공고 원문 보기 ↗</a><a class="secondary" target="_blank" rel="noopener noreferrer" href="${esc(route)}">차량 경로 보기 ↗</a></div><p class="source-note">출처: ${esc(j.source)} · ${esc(j.status)}<br>검토 이유는 공고를 바탕으로 한 판단이며 회사의 근무환경을 보증하지 않습니다.</p></div></details></div></article>`}).join(''):'<div class="empty">조건에 맞는 공고가 없습니다.<br>검색어나 필터를 바꿔보세요.</div>';
document.querySelectorAll('[data-expand]').forEach(b=>b.onclick=()=>{const id=b.dataset.expand;const open=!expanded.has(id);if(open)expanded.add(id);else expanded.delete(id);document.getElementById('preview-'+id).hidden=!open;b.setAttribute('aria-expanded',String(open));b.querySelector('.expand-hint').textContent=open?'요약 접기 −':'요약 보기 ＋'});document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{const id=b.dataset.save;saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];Archive.saved=saved;Archive.persist();render()});Archive.bind();}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',3000)}
function classify(j){const t=j.role+' '+j.duties;if(/경리|회계|급여.*보험/.test(t))return '경리·회계';if(/간호|입소자|진료.*보조/.test(t))return '의료·돌봄';if(/교육|출결|수강/.test(t))return '교육행정';if(/예약|일정.*조율/.test(t))return '예약·일정';if(/수발주|주문|납기/.test(t))return '주문·수발주';if(/인바운드|전화 응대|고객지원/.test(t))return '고객·접수';if(/사무|행정|문서/.test(t))return '사무·행정';return '기타·확인 필요'}
document.querySelector('.filters').innerHTML=['all',...new Set(Archive.jobs.map(classify)),'stretch'].map(x=>`<button data-filter="${esc(x)}" class="${x==='all'?'active':''}">${esc(x==='all'?'전체':x==='stretch'?'조건 좋은 제안':x)}</button>`).join('');
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('selected',x===b));filter='all';$('#search').value='';document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'));$('#criteria').hidden=tab!=='criteria';$('#results').hidden=tab==='criteria';render()});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));render()});$('#search').oninput=render;$('#update').onclick=()=>$('#help').showModal();$('#close-help').onclick=()=>$('#help').close();
if(Date.now()-new Date(window.JOB_UPDATE?.id||'2026-09-17T03:28+09:00').getTime()>86400000*2){$('#stale').hidden=false;$('#stale').textContent='공고 확인 후 2일 이상 지났습니다. 오늘 모집 여부를 다시 확인해주세요.'}render();

$('#update-mobile').onclick=()=>$('#help').showModal();Archive.bindBackup();

$('#commute-origin').value=commuteOrigin;
$('#save-origin').onclick=()=>{commuteOrigin=$('#commute-origin').value.trim();try{localStorage.setItem('commute-origin',commuteOrigin);toast('출발지를 이 브라우저에 저장했습니다.')}catch{toast('저장 제한: 현재 화면에서만 사용합니다.')}render()};
