const Archive=(()=>{
const key='next-job-records-v2';let data={records:{},saved:[]};let storageOK=true;
try{const old=JSON.parse(localStorage.getItem(key)||'null');if(old&&old.records&&Array.isArray(old.saved))data=old;else data.saved=JSON.parse(localStorage.getItem('next-job-saved')||'[]')}catch{storageOK=false}
const now=(window.JOB_UPDATE?.id||'2026-09-17').slice(0,10);
// Keep explicit archive entries in JOBS on every manual update. Missing is not closed.
JOBS.forEach(j=>{j.checkedAt=j.checkedAt||'2026-09-17';j.recruitment=j.recruitment||(j.id==='crane'||j.id==='staffs'?'모집 중':'확인 필요');if(j.id==='bogum'){j.outOfScope=true;j.group='이전 후보 보관'}if(j.id==='staffs')j.checks+=' · 판매 목표·고객 유치 없는 내부 행정인지 확인';const old=data.records[j.id];const fields=['pay','hours','contract','duties','deadlineText'];const changes=old?fields.filter(k=>old.snapshot[k]!==j[k]).map(k=>({at:now,field:k,before:old.snapshot[k],after:j[k]})):[];data.records[j.id]={snapshot:{...j},progress:old?.progress||'검토 중',note:old?.note||'',history:[...(old?.history||[]),...changes],firstSeen:old?.firstSeen||now};});
const api={get jobs(){return Object.values(data.records).map(r=>r.snapshot)},get saved(){return data.saved},set saved(v){data.saved=v},persist(){try{localStorage.setItem(key,JSON.stringify(data));storageOK=true}catch{storageOK=false;alert('저장 공간이 제한되어 기록을 보관하지 못했습니다. 내 기록 백업을 이용해주세요.')}},state(j){if(j.recruitment==='마감'||j.recruitment==='원문 삭제')return j.recruitment;if(j.deadline&&Date.now()>new Date(j.deadline+'T23:59:59+09:00').getTime())return '마감일 경과';if(!JOBS.some(x=>x.id===j.id))return '확인 필요 · 검색 누락';return j.recruitment||'확인 필요'},management(j){const r=data.records[j.id];const labels={pay:'급여',hours:'시간',contract:'고용형태',duties:'업무',deadlineText:'마감'};return `<div class="record-meta">최초 수집 ${esc(r.firstSeen)} · 마지막 자료 확인 ${esc(j.checkedAt||'미상')}${r.history.length?' · 조건 변경 '+r.history.length+'건':''}</div>${data.saved.includes(j.id)?`<section class="management"><label>내 진행 상태<select data-progress="${esc(j.id)}" aria-label="${esc(j.company)} 진행 상태">${['검토 중','문의 예정','지원 완료','면접 예정','보류','검토 종료'].map(x=>`<option ${r.progress===x?'selected':''}>${x}</option>`).join('')}</select></label><label>내 메모<textarea data-note="${esc(j.id)}" aria-label="${esc(j.company)} 메모" placeholder="문의할 내용이나 면접 일정을 적어두세요">${esc(r.note)}</textarea></label><span class="note-state" role="status">입력하면 이 브라우저에 저장됩니다.</span></section>`:''}${r.history.length?`<details class="history"><summary>조건 변경 이력</summary>${r.history.map(h=>`<p>${esc(h.at)} ${esc(labels[h.field]||h.field)}: ${esc(h.before)} → ${esc(h.after)}</p>`).join('')}</details>`:''}`},bind(){document.querySelectorAll('[data-progress]').forEach(e=>e.onchange=()=>{data.records[e.dataset.progress].progress=e.value;api.persist()});document.querySelectorAll('[data-note]').forEach(e=>e.oninput=()=>{data.records[e.dataset.note].note=e.value;api.persist();e.closest('.management').querySelector('.note-state').textContent=storageOK?'저장됨 · 이 브라우저':'저장 실패'})},bindBackup(){document.querySelector('#export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='job-records-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};document.querySelector('#import').onchange=async e=>{try{const x=JSON.parse(await e.target.files[0].text());if(!x.records||!Array.isArray(x.saved))throw Error();for(const [id,r] of Object.entries(x.records)){if(!/^[a-z0-9_-]+$/i.test(id)||!r.snapshot||r.snapshot.id!==id||typeof r.note!=='string'||!Array.isArray(r.history)||!/^https:\/\//.test(r.snapshot.url))throw Error()}if(!confirm('백업 파일의 메모와 진행 상태를 병합할까요? 같은 공고의 개인 기록은 백업 내용으로 바뀝니다.'))return;for(const [id,r]of Object.entries(x.records)){data.records[id]=data.records[id]?{...data.records[id],note:r.note,progress:r.progress}:r}data.saved=[...new Set([...data.saved,...x.saved.filter(id=>data.records[id])])];api.persist();location.reload()}catch{alert('올바른 대시보드 백업 파일인지 확인해주세요.')}}}};
api.persist();return api;
})();
