// Manual source review; preserve listing IDs and personal browser records.
window.JOB_UPDATE={"id":"2026-09-17T03:57:04+09:00","newIds":["ipc-dpworld-49929461","manpower-lg-49606850"],"changedIds":["baeksan"],"closedIds":[]};
window.JOBS=[
  {
    "id": "crane",
    "company": "크레인클라쓰",
    "role": "사무 직원",
    "category": "office",
    "group": "우선 검토",
    "region": "안성 원곡면",
    "address": "경기도 안성시 원곡면 원당로 23",
    "business": "건설기계 도급·대여 관련 업체",
    "pay": "월 230~250만 원",
    "annual": "연 2,760~3,000만 원 환산 · 이전 대비 −120~+120만 원",
    "hours": "월~금 09:00~17:00",
    "contract": "정규직",
    "benefit": "4대 보험",
    "duties": "공고상 사무업무. 담당 범위와 업무분장은 구체적으로 확인 필요.",
    "why": "주중 5일·17시 퇴근으로 시간 조건이 좋고, 급여 범위가 이전 연봉과 가깝습니다.",
    "caution": "제목은 월 250만 원, 상세는 230~250만 원. 실제 제안 급여와 업무분장 확인.",
    "checks": "인수인계 담당자, 단독 사무 여부, 현장 업무 병행, 수습 급여, 연봉 조정 기준",
    "deadline": null,
    "deadlineText": "상시모집 · 조기 마감 가능",
    "source": "알바천국",
    "status": "원문 재확인 · 모집 안내 유지",
    "url": "https://www.alba.co.kr/job/Detail?adid=146669468",
    "checkedAt": "2026.09.17 03:57",
    "recruitment": "모집 중"
  },
  {
    "id": "staffs",
    "company": "스탭스",
    "role": "외국계 기업 영업관리팀 행정 사무",
    "category": "office",
    "stretch": true,
    "group": "급여 좋은 제안",
    "region": "평택 진위면",
    "address": "경기도 평택시 진위면 진위산단로 64",
    "business": "스탭스 채용 / 외국계 기업 근무. 실제 사용사업주 업체명 확인 필요.",
    "pay": "월 270만 원",
    "annual": "연 3,240만 원 환산 · 이전 대비 +360만 원",
    "hours": "월~금 08:30~17:30",
    "contract": "파견 계약 2년",
    "benefit": "식사 제공·4대 보험",
    "duties": "영업관리팀 행정 사무. 엑셀·PPT·ERP 관련 역량 우대.",
    "why": "주중 고정 근무와 이전보다 높은 급여. 사무 경험을 확장할 후보입니다.",
    "caution": "관련 경력 2년 이상 요구 · 파견 2년 · 출근 30분 빠름.",
    "checks": "기존 사무 경력 인정 범위, 실제 배치 회사, 계약 종료 후 고용, 출퇴근 경로",
    "deadline": "2026-09-30",
    "deadlineText": "2026.09.30 마감",
    "source": "사람인",
    "status": "원문 재확인 · 모집 안내 유지",
    "url": "https://m.saramin.co.kr/job-search/view?rec_idx=54914997",
    "checkedAt": "2026.09.17 03:57",
    "recruitment": "모집 중"
  },
  {
    "id": "baeksan",
    "company": "백산씨앤씨",
    "role": "건설회사 경리·회계",
    "category": "office",
    "stretch": true,
    "group": "경력 조건 확인",
    "region": "평택 용이동",
    "address": "경기도 평택시 현신7길 30",
    "business": "건설업체. 상세 사업 범위 확인 필요.",
    "pay": "월 270~320만 원 · 협의 가능",
    "annual": "연 3,240~3,840만 원 환산 · 이전 대비 +360~+960만 원",
    "hours": "주 5일 09:00~18:00 · 월~금 여부 확인",
    "contract": "기간의 정함 없는 근로계약",
    "benefit": "식대 지원·4대 보험·퇴직금",
    "duties": "급여·4대 보험·세금계산서·부가세 자료·일용직 급여·자금 및 원가 관련 회계.",
    "why": "고용기간과 급여 조건은 매력적입니다. 회계 실무 역량을 갖춘 경우에 검토할 후보입니다.",
    "caution": "회계 경력 3년 우대. 단순 사무보조보다 전문성이 높아 현재 경력과 차이가 큽니다.",
    "checks": "회계 경력 필수 여부, 교육·인수인계, 혼자 전체 회계를 맡는지, 근무 요일",
    "deadline": null,
    "deadlineText": "고용24 채용시까지 / 알바천국 2026.10.17 표기 · 확인 필요",
    "source": "고용24",
    "status": "고용24 원문·알바천국 연계 공고 재확인 · 협의 가능 및 마감 표기 차이 보완",
    "url": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?infoTypeCd=VALIDATION&infoTypeGroup=tb_workinfoworknet&wantedAuthNo=K180612608180017",
    "checkedAt": "2026.09.17 03:57",
    "recruitment": "모집 중",
    "salaryType": "negotiable",
    "employees": "고용24 근로자 수 1명 기재 · 실제 현재 인원 확인 필요"
  },
  {
    "id": "suseong",
    "company": "수성정보통신",
    "role": "온라인 사무·인바운드 상담",
    "category": "office",
    "group": "조건부 검토",
    "region": "평택 합정동",
    "address": "경기도 평택시 조개터로2번길 1",
    "business": "카드 단말기 관련 온라인 업무 업체",
    "pay": "월 220만 원",
    "annual": "연 2,640만 원 환산 · 이전 대비 −240만 원",
    "hours": "월~금 09:00~18:00",
    "contract": "초기 1개월 계약 후 연장 조건 확인",
    "benefit": "식사·교통 지원 공고 기재, 지급 범위 확인",
    "duties": "카드 단말기 관련 온라인 업무, 인바운드 전화 응대, 컴퓨터·엑셀 사무.",
    "why": "주중 주간 사무 업무로 검토할 수 있습니다. 전화 응대 경험을 활용할 여지가 있습니다.",
    "caution": "간헐적 야근. 계약 갱신 구조가 복잡해 장기 고용 기준에서는 우선순위가 낮습니다.",
    "checks": "1개월 이후 계약기간 및 3개월 단위 재작성 사유, 야근 횟수·수당, 업무분장",
    "deadline": null,
    "deadlineText": "상시모집",
    "source": "알바천국",
    "status": "원문 재확인 · 모집 안내 유지",
    "url": "https://www.alba.co.kr/job/Detail?adid=146580300",
    "checkedAt": "2026.09.17 03:57",
    "recruitment": "모집 중"
  },
  {
    "id": "bogum",
    "company": "보금자리요양원",
    "role": "간호조무사",
    "category": "medical",
    "group": "의료 경력 활용",
    "region": "평택 신대동",
    "address": "경기도 평택시 신대고잔길 55-14",
    "business": "노인 요양시설",
    "pay": "월 230만 원",
    "annual": "연 2,760만 원 환산 · 이전 대비 −120만 원",
    "hours": "주 5일 09:00~18:00 · 월~금 여부 확인",
    "contract": "기간의 정함 없는 근로계약",
    "benefit": "4대 보험·퇴직금 / 식사 미제공",
    "duties": "입소자 건강 관리·기록, 생활 지원, 보호자 소통 등.",
    "why": "간호조무사 경험을 활용하고, 고용기간에 제한이 없는 후보입니다.",
    "caution": "좌식 사무직이 아닙니다. 생활 지원 범위와 주말 근무 가능성 확인이 필요합니다.",
    "checks": "주말 순환근무, 이동·신체보조 비중, 간호 인력 배치, 업무 분장",
    "deadline": null,
    "deadlineText": "채용시까지",
    "source": "고용24",
    "status": "원문 재접속 실패 · 이전 자료 유지 · 마감으로 단정하지 않음",
    "url": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?infoTypeCd=VALIDATION&infoTypeGroup=tb_workinfoworknet&wantedAuthNo=KEC0092609140002",
    "checkedAt": "2026.09.17 03:57",
    "recruitment": "확인 필요"
  },
  {
    "id": "ipc-dpworld-49929461",
    "company": "아이피시 · DP월드 평택센터",
    "role": "물류센터 사무보조",
    "category": "office",
    "stretch": true,
    "group": "급여 좋은 제안",
    "region": "평택 합정동",
    "address": "경기도 평택시 합정동 173-11 DP월드 평택센터",
    "business": "아이피시 파견 채용 / 실제 근무 DP월드로지스틱스 평택센터",
    "employees": "아이피시 전체 501~1,000명 이하(잡코리아) · 평택센터 인원 미확인",
    "pay": "월 258만 원 이상",
    "annual": "연 3,096만 원 이상 단순 환산 · 이전 대비 +216만 원 이상",
    "hours": "월~금 08:00~17:00 · 부서별 09~18 / 10~19 가능",
    "contract": "파견직 2년",
    "benefit": "복리후생 상세 확인 필요",
    "duties": "공고 모집분야는 사무보조. 실제 전산·문서 업무 범위와 물류현장 작업 병행 여부는 확인 필요.",
    "why": "합정동 고정 사업장 사무보조이며 경력무관. 제시 월급이 이전 연봉의 월 환산액보다 높습니다.",
    "caution": "09~18 배치 확정 필요. 08시 출근 또는 19시 퇴근 가능 · 파견 2년으로 장기 고용 보장 없음.",
    "checks": "09~18 고정 배치, 영업·포장·상하차 없는지, 좌식 비중, 고용주와 2년 후 계약, 출근 시간대 통근",
    "deadline": null,
    "deadlineText": "상시채용 · 2026.09.04 등록",
    "source": "잡코리아",
    "url": "https://m.jobkorea.co.kr/Recruit/GI_Read/49929461?PageGbn=MST&sc=226",
    "addedBatch": "2026-09-17T03:57:04+09:00",
    "checkedAt": "2026.09.17 03:57",
    "recruitment": "모집 중",
    "status": "공개 원문 모집 안내 확인 · 실제 결원·근무환경은 문의 필요"
  },
  {
    "id": "manpower-lg-49606850",
    "company": "맨파워코리아 · LG전자",
    "role": "LG전자 사무보조·일반총무 인재풀",
    "category": "office",
    "stretch": true,
    "group": "급여 좋은 제안",
    "region": "평택 진위면",
    "address": "경기도 평택시 진위면 엘지로 222 LG디지털파크",
    "business": "맨파워코리아 채용 / LG전자 사업장 파견 사무보조 인재풀 모집",
    "employees": "맨파워코리아 전체 1,001~10,000명 이하(잡코리아) · 배치 부서 인원 미확인",
    "pay": "연 3,300만 원",
    "annual": "이전 연봉 대비 +420만 원 · 월 평균 275만 원 환산",
    "hours": "월~금 08:00~17:00",
    "contract": "계약·파견직 24개월",
    "benefit": "제목에 셔틀버스 명시 · 노선과 대상 확인 필요",
    "duties": "모집분야 사무보조·일반총무. 인재풀 등록이므로 실제 배치 부서와 담당 업무는 추후 확인 필요.",
    "why": "경력·학력 무관의 주중 사무직 후보로, 제시 연봉이 이전보다 높습니다.",
    "caution": "인재풀 상시 모집으로 즉시 입사 보장 없음. 08시 출근 · 24개월 계약 · 통근 30분 이내 여부 미확인.",
    "checks": "현재 실제 결원, 담당 업무와 비영업 여부, 셔틀 노선, 출근시간 조정, 계약 종료 이후, 급여 포함 항목",
    "deadline": null,
    "deadlineText": "상시채용 인재풀 · 2026.07.20 등록",
    "source": "잡코리아",
    "url": "https://www.jobkorea.co.kr/Recruit/GI_Read/49606850?Oem_Code=C1&listno=4280&logpath=1&stext=%ED%98%91%ED%9A%8C",
    "addedBatch": "2026-09-17T03:57:04+09:00",
    "checkedAt": "2026.09.17 03:57",
    "recruitment": "모집 중",
    "status": "공개 원문 모집 안내 확인 · 실제 결원·근무환경은 문의 필요"
  }
];
window.NAVER_DESTINATIONS={"crane":"3zp38k,2Aq6Sz,%EA%B2%BD%EA%B8%B0%20%EC%95%88%EC%84%B1%EC%8B%9C%20%EC%9B%90%EA%B3%A1%EB%A9%B4%20%EC%9B%90%EB%8B%B9%EB%A1%9C%2023,,ADDRESS_POI","staffs":"3zm7Ft,2AttwH,%EA%B2%BD%EA%B8%B0%20%ED%8F%89%ED%83%9D%EC%8B%9C%20%EC%A7%84%EC%9C%84%EB%A9%B4%20%EC%A7%84%EC%9C%84%EC%82%B0%EB%8B%A8%EB%A1%9C%2064,,ADDRESS_POI","baeksan":"3zoN1L,2AogF9,%EA%B2%BD%EA%B8%B0%20%ED%8F%89%ED%83%9D%EC%8B%9C%20%ED%98%84%EC%8B%A07%EA%B8%B8%2030,,ADDRESS_POI","suseong":"3zmPhW,2AnKLN,%EA%B2%BD%EA%B8%B0%20%ED%8F%89%ED%83%9D%EC%8B%9C%20%EC%A1%B0%EA%B0%9C%ED%84%B0%EB%A1%9C2%EB%B2%88%EA%B8%B8%201,,ADDRESS_POI","bogum":"3zlkXH,2Ao4kC,%EA%B2%BD%EA%B8%B0%20%ED%8F%89%ED%83%9D%EC%8B%9C%20%EC%8B%A0%EB%8C%80%EA%B3%A0%EC%9E%94%EA%B8%B8%2055-14,,ADDRESS_POI"};
