// Advance batch id only after a real research update; record addedBatch on newly accepted jobs.
window.JOB_UPDATE={id:'2026-09-17T03:28+09:00',newIds:[],changedIds:[]};
window.JOBS=[
{id:'crane',company:'크레인클라쓰',role:'사무 직원',category:'office',group:'우선 검토',region:'안성 원곡면',address:'경기도 안성시 원곡면 원당로 23',business:'건설기계 도급·대여 관련 업체',pay:'월 230~250만 원',annual:'연 2,760~3,000만 원 환산 · 이전 대비 −120~+120만 원',hours:'월~금 09:00~17:00',contract:'정규직',benefit:'4대 보험',duties:'공고상 사무업무. 담당 범위와 업무분장은 구체적으로 확인 필요.',why:'주중 5일·17시 퇴근으로 시간 조건이 좋고, 급여 범위가 이전 연봉과 가깝습니다.',caution:'제목은 월 250만 원, 상세는 230~250만 원. 실제 제안 급여와 업무분장 확인.',checks:'인수인계 담당자, 단독 사무 여부, 현장 업무 병행, 수습 급여, 연봉 조정 기준',deadline:null,deadlineText:'상시모집 · 조기 마감 가능',source:'알바천국',status:'2026.09.17 재검색 · 원문 재확인',url:'https://www.alba.co.kr/job/Detail?adid=146669468'},
{id:'staffs',company:'스탭스',role:'외국계 기업 영업관리팀 행정 사무',category:'office',stretch:true,group:'급여 좋은 제안',region:'평택 진위면',address:'경기도 평택시 진위면 진위산단로 64',business:'스탭스 채용 / 외국계 기업 근무. 실제 사용사업주 업체명 확인 필요.',pay:'월 270만 원',annual:'연 3,240만 원 환산 · 이전 대비 +360만 원',hours:'월~금 08:30~17:30',contract:'파견 계약 2년',benefit:'식사 제공·4대 보험',duties:'영업관리팀 행정 사무. 엑셀·PPT·ERP 관련 역량 우대.',why:'주중 고정 근무와 이전보다 높은 급여. 사무 경험을 확장할 후보입니다.',caution:'관련 경력 2년 이상 요구 · 파견 2년 · 출근 30분 빠름.',checks:'기존 사무 경력 인정 범위, 실제 배치 회사, 계약 종료 후 고용, 출퇴근 경로',deadline:'2026-09-30',deadlineText:'2026.09.30 마감',source:'사람인',status:'2026.09.17 재검색 · 원문 재확인',url:'https://m.saramin.co.kr/job-search/view?rec_idx=54914997'},
{id:'baeksan',company:'백산씨앤씨',role:'건설회사 경리·회계',category:'office',stretch:true,group:'경력 조건 확인',region:'평택 용이동',address:'경기도 평택시 현신7길 30',business:'건설업체. 상세 사업 범위 확인 필요.',pay:'월 270~320만 원',annual:'연 3,240~3,840만 원 환산 · 이전 대비 +360~+960만 원',hours:'주 5일 09:00~18:00 · 월~금 여부 확인',contract:'기간의 정함 없는 근로계약',benefit:'식대 지원·4대 보험·퇴직금',duties:'급여·4대 보험·세금계산서·부가세 자료·일용직 급여·자금 및 원가 관련 회계.',why:'고용기간과 급여 조건은 매력적입니다. 회계 실무 역량을 갖춘 경우에 검토할 후보입니다.',caution:'회계 경력 3년 우대. 단순 사무보조보다 전문성이 높아 현재 경력과 차이가 큽니다.',checks:'회계 경력 필수 여부, 교육·인수인계, 혼자 전체 회계를 맡는지, 근무 요일',deadline:null,deadlineText:'채용시까지',source:'고용24',status:'2026.09.17 재검색 · 재접속 제한, 이전 자료 유지 · 모집 여부 재확인 필요',url:'https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?infoTypeCd=VALIDATION&infoTypeGroup=tb_workinfoworknet&wantedAuthNo=K180612608180017'},
{id:'suseong',company:'수성정보통신',role:'온라인 사무·인바운드 상담',category:'office',group:'조건부 검토',region:'평택 합정동',address:'경기도 평택시 조개터로2번길 1',business:'카드 단말기 관련 온라인 업무 업체',pay:'월 220만 원',annual:'연 2,640만 원 환산 · 이전 대비 −240만 원',hours:'월~금 09:00~18:00',contract:'초기 1개월 계약 후 연장 조건 확인',benefit:'식사·교통 지원 공고 기재, 지급 범위 확인',duties:'카드 단말기 관련 온라인 업무, 인바운드 전화 응대, 컴퓨터·엑셀 사무.',why:'주중 주간 사무 업무로 검토할 수 있습니다. 전화 응대 경험을 활용할 여지가 있습니다.',caution:'간헐적 야근. 계약 갱신 구조가 복잡해 장기 고용 기준에서는 우선순위가 낮습니다.',checks:'1개월 이후 계약기간 및 3개월 단위 재작성 사유, 야근 횟수·수당, 업무분장',deadline:null,deadlineText:'상시모집',source:'알바천국',status:'2026.09.17 재검색 · 재접속 제한, 이전 자료 유지 · 모집 여부 재확인 필요',url:'https://www.alba.co.kr/job/Detail?adid=146580300'},
{id:'bogum',company:'보금자리요양원',role:'간호조무사',category:'medical',group:'의료 경력 활용',region:'평택 신대동',address:'경기도 평택시 신대고잔길 55-14',business:'노인 요양시설',pay:'월 230만 원',annual:'연 2,760만 원 환산 · 이전 대비 −120만 원',hours:'주 5일 09:00~18:00 · 월~금 여부 확인',contract:'기간의 정함 없는 근로계약',benefit:'4대 보험·퇴직금 / 식사 미제공',duties:'입소자 건강 관리·기록, 생활 지원, 보호자 소통 등.',why:'간호조무사 경험을 활용하고, 고용기간에 제한이 없는 후보입니다.',caution:'좌식 사무직이 아닙니다. 생활 지원 범위와 주말 근무 가능성 확인이 필요합니다.',checks:'주말 순환근무, 이동·신체보조 비중, 간호 인력 배치, 업무 분장',deadline:null,deadlineText:'채용시까지',source:'고용24',status:'2026.09.17 재검색 · 재접속 제한, 이전 자료 유지 · 모집 여부 재확인 필요',url:'https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?infoTypeCd=VALIDATION&infoTypeGroup=tb_workinfoworknet&wantedAuthNo=KEC0092609140002'}
];
